name: CI - Pull Request
on:
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16.10"
          check-latest: true

      - name: Install Node Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
